/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-07-04 12:01:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class WriteForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Board ORI 예제 글쓰기 폼</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function writeFormCheck() {\r\n");
      out.write("\t\r\n");
      out.write("\tif($trim($(\"#writer\").val()) == null || $trim($(\"#writer\").val()) == \"\"){\r\n");
      out.write("\t    alert(\"글쓴이 입력해 주세요!\");\r\n");
      out.write("\t    $(\"#writer\").focus();\r\n");
      out.write("\t    return false;\r\n");
      out.write("  \t}\r\n");
      out.write("\tif($(\"#subject\").val() == null || $(\"#subject\").val() == \"\"){\r\n");
      out.write("        alert(\"글제목 입력해 주세요!\");\r\n");
      out.write("        $(\"#subject\").focus();\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\tif($(\"#content\").val() == null || $(\"#content\").val() == \"\"){\r\n");
      out.write("        alert(\"글내용을  입력해 주세요!\");\r\n");
      out.write("        $(\"#content\").focus();\r\n");
      out.write("        return false;\r\n");
      out.write("      }\t\t\r\n");
      out.write("      return true;\r\n");
      out.write("}//writeFormCheck() end\r\n");
      out.write("\r\n");
      out.write("function flagCheck(){\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\tif($(\"#flag\").val() == 0 ){\r\n");
      out.write("\talert(\"밸류 0\");\r\n");
      out.write("\t//document.writeForm.action=\"write.do\"\r\n");
      out.write("\t//document.writeForm.action=\"write.do\"\r\n");
      out.write("\t//alert(document.writeForm.action);\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#writeForm\").attr('action', 'write.do');\r\n");
      out.write("\t\r\n");
      out.write("\t//alert($(\"#writeForm\").val());\r\n");
      out.write("\t$(\"#writeForm\").submit();\r\n");
      out.write("\t//document.writeForm.submit;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif($(\"#flag\").val() == 1 ){\r\n");
      out.write("\t\talert(\"밸류 1\");\r\n");
      out.write("\t\t//document.writeForm.action=\"reply.do\"\r\n");
      out.write("\t\t$(\"#writeForm\").attr('action', 'reply.do');\r\n");
      out.write("\t\t$(\"#writeForm\").submit();\r\n");
      out.write("\t\t//alert($(\"#writeForm\").val());\r\n");
      out.write("\t\t//document.writeForm.submit;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("  table{\r\n");
      out.write("  line-height: 40px; padding: 5px; border-spacing: 0px;\r\n");
      out.write("  margin: auto; background-color: orange;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2 align=\"center\">게시판 글쓰기폼</h2>\r\n");
      out.write("\t<a href=\"list.do\">리스트</a>\r\n");
      out.write("    <!-- \r\n");
      out.write("    <form name=\"writeForm\" method=\"post\" action=\"write.do\" onsubmit=\"return writeFormCheck()\">\t\r\n");
      out.write(" \t -->\r\n");
      out.write(" \t <form id=\"writeForm\" name=\"writeForm\" method=\"post\" action=\"write.do\" >\r\n");
      out.write(" \t \r\n");
      out.write(" \t<table align=\"center\" width=\"800\">\r\n");
      out.write(" \t\r\n");
      out.write(" \t\t<tr>\r\n");
      out.write("          <td>글쓴이</td>\r\n");
      out.write("          <td><input type=\"text\" id=\"writer\" name=\"writer\" size=\"10\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${falg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /> </td>\r\n");
      out.write("        </tr>\r\n");
      out.write(" \t\t<tr>\r\n");
      out.write("          <td>글제목</td>\r\n");
      out.write("          <td><input type=\"text\" id=\"subject\" name=\"subject\" size=\"30\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDto.subject }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/> </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>이메일</td>\r\n");
      out.write("          <td><input type=\"text\" id=\"email\" name=\"email\" size=\"30\"/> </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>글내용</td>\r\n");
      out.write("          <td> <textArea name=\"content\" id=\"content\" rows=\"13\" cols=\"40\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDto.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textArea> </td>\r\n");
      out.write("        </tr>\r\n");
      out.write(" \t\t<tr>\r\n");
      out.write("          <td>암호</td>\r\n");
      out.write("          <td><input type=\"password\" id=\"password\" name=\"password\" size=\"10\"/> </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("          <td colspan=\"2\" align=\"center\">\r\n");
      out.write("            <!-- \r\n");
      out.write("            <input type=\"button\" value=\"글등록\" onclick=\"writeFormCheck()\">\r\n");
      out.write("            \r\n");
      out.write("            <input type=\"submit\" value=\"글등록\" >\r\n");
      out.write("            -->\r\n");
      out.write("            <input type=\"button\" value=\"글등록\" onclick=\"flagCheck()\">\r\n");
      out.write("            \r\n");
      out.write("            <input type=\"reset\" value=\"입력한내용취소\">\r\n");
      out.write("            <input type=\"hidden\" id=\"flag\" name=\"flag\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDto.flag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("            \r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t</table>\t\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
